name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.7.0

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build Project
      run: yarn build

    - name: Generate SHA-256 Checksums
      run: |
        cd build/bin
        for file in *; do
          shasum -a 256 "$file" >> checksums.txt
        done

    # Upload packaged binaries as a release artifact
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: build/bin/

    # Create a GitHub release and upload the artifacts
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/bin/*
        token: ${{ secrets.GITHUB_TOKEN }}

